services:
  db:
    image: couchdb
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=YOURPASSWORD
    volumes:
        - ./dbdata:/opt/couchdb/data
        - ./couchdb-config:/opt/couchdb/etc/local.d

  backend:
    container_name: wanja_top10_backend
    build: ./backend
    depends_on:
      - db

  frontend:
    container_name: wanja_top10_frontend
    build: ./frontend
    depends_on:
      - backend

  rp:
    container_name: wanja_top10_rp
    build: ./reverseproxy
    ports:
      - 8089:80

