version: '3'

services:
  backend:
    container_name: wanja_top10_backend
    build: ./backend

  frontend:
    container_name: wanja_top10_frontend
    build: ./frontend

  rp:
    container_name: wanja_top10_rp
    build: ./reverseproxy
    ports:
      - 8089:80

